{% set version = "4.8.10" %}
{% set name = "gap" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://www.gap-system.org/pub/gap/gap48/tar.gz/gap4r8p10_2018_01_15-13_02.tar.gz
  sha256: fc0dac32d196a825be5b4cab6a970aad58f1d16ca2870bd0381c94c85e7a9e5b
  patches:
    # Patches from https://github.com/sagemath/sage
    # Set GAP_MEM
    - patches/gap_shi.patch
    # fix infinite loop in writeandcheck() when writing an error message fails.
    - patches/writeandcheck.patch
    # https://github.com/gap-system/gap/pull/448
    - patches/448.patch
    # https://github.com/gap-system/gap/pull/1188
    - patches/path.patch
    # we don't install some of the default packages
    - patches/nodefaultpackages.patch

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
  host:
    - gmp
    - readline
    - ncurses
  run:
    - gmp
    - readline
    - ncurses

test:
  commands:
    - gap -h

about:
  home: https://www.gap-system.org/
  license: GPLv2
  license_file: LICENSE
  summary: GAP - Groups, Algorithms, Programming, a System for Computational Discrete Algebra
  dev_url: https://github.com/gap-system/gap
  doc_url: https://www.gap-system.org/Manuals/doc/ref/chap0.html

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
