{% set version = "4.10.2" %}
{% set name = "gap-split" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://www.gap-system.org/pub/gap/gap-{{ ".".join(version.split(".")[:2]) }}/tar.gz/gap-{{ version }}.tar.gz
  sha256: 11175bed0234101643d510d4ab94c44db30bd303bfe63d86b9b86ae67cff9e49
  patches:
    - patches/make_install.patch

build:
  number: 4
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool  # FIXME: this should not be necessary for GAP itself, unless you build from git (but you don't, do you?); but perhaps some package needs it?
    - m4       # FIXME: same as with libtool
    - autoconf   # for simpcomp and NormalizInterface    # FIXME: simpcomp 2.1.9 in GAP 4.10.2 should not need this (and NormalizInterface 1.1.0 in GAP 4.11 won't either)
    - automake   # for NormalizInterface # FIXME: shouldn't be need with NormalizInterface 1.1.0 or later in GAP 4.11
    - git        # for NormalizInterface # FIXME: shouldn't be need with NormalizInterface 1.1.0 or later in GAP 4.11
    - make
  host:
    # Since we are using bin/buildpackages.sh to build all packages at once,
    # these requirements are needed.
    - gmp
    - readline {{ readline }}
    - ncurses    # for Browse
    - curl       # for curlInterface
    - boost-cpp  # for NormalizInterface
    - mpfr       # for float
    - mpfi       # for float
    - mpc        # for float
    #- fplll     # for float
    - pari       # for alnuth
    - zeromq     # for ZeroMQInterface
    - linbox     # linboxing  # FIXME: linboxing is no longer shipped with GAP since 4.10, so you can drop this
    - libsemigroups   # for Semigroups
    - planarity  # for digraphs
    - normaliz   # for NormalizInterface   # FIXME: huh -- if you link NormalizInterface against your own normaliz, then you shouldn't need boost, automake, autoconf for it... something does not add up here
    - zlib

outputs:
  - name: gap-core
    script: install-core.sh
    requirements:
      build:    
        - {{ compiler('cxx') }}  # silly question (as I have no idea how conda meta.yml works): how do these requirements relate to the ones given above? Which ones need to be repeated here, and which not?
        - libtool
        - make
      host:
        - gmp
        - readline {{ readline }}
        - zlib
      run:
        - gmp
        - readline {{ readline }}
        - zlib
    test:
      commands:
        - gap -h

  - name: gap-defaults
    script: install-defaults.sh
    # ... and why does this "output" not need any requirements, when the one before and the one after apparently do need them?
    requirements:
      host:
        - {{ pin_subpackage('gap-core', exact=True) }}
      run:
        - {{ pin_subpackage('gap-core', exact=True) }}
    test:
      commands:
        - echo "TODO - test a package here"

  - name: gap
    script: install-full.sh
    requirements:
      build:    
        - {{ compiler('cxx') }}
        - libtool
        - make
      host:
        - gmp
        - readline {{ readline }}
        - ncurses    # for Browse
        - libcurl    # for curlInterface
        - boost-cpp  # for NormalizInterface
        - mpfr       # for float
        - mpfi       # for float
        - mpc        # for float
        #- fplll     # for float
        - pari       # for alnuth
        - zeromq     # for ZeroMQInterface
        - linbox     # for linboxing
        - libsemigroups   # for Semigroups
        - planarity  # for digraphs
        - normaliz   # for NormalizInterface
        - {{ pin_subpackage('gap-core', exact=True) }}
        - {{ pin_subpackage('gap-defaults', exact=True) }}
        # For JupyterKernel
        - python *
        - pip
      run:
        - gmp
        - readline {{ readline }}
        - ncurses    # for Browse
        - libcurl    # for curlInterface
        - mpfr       # for float
        - mpfi       # for float
        - mpc        # for float
        #- fplll     # for float
        - pari       # for alnuth
        - zeromq     # for ZeroMQInterface
        - linbox     # for linboxing
        - {{ pin_compatible('libsemigroups') }}   # for Semigroups
        - {{ pin_compatible('planarity') }}       # for digraphs
        - {{ pin_compatible('normaliz') }}        # for NormalizInterface
        - {{ pin_subpackage('gap-core', exact=True) }}
        - {{ pin_subpackage('gap-defaults', exact=True) }}
    test:
      commands:
        - echo "TODO - test a package here"

about:
  home: https://www.gap-system.org/
  license: GPLv2
  license_file: LICENSE
  summary: GAP - Groups, Algorithms, Programming, a System for Computational Discrete Algebra
  dev_url: https://github.com/gap-system/gap
  doc_url: https://www.gap-system.org/Manuals/doc/ref/chap0.html

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
