{% set version = "4.15.1" %}
{% set name = "gap-split" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/gap-system/gap/releases/download/v{{ version }}/gap-{{ version }}.tar.gz
  sha256: 6049d53e99b12e25c2d848db21ac4a06380a46fe4c4157243d556fe06930042c
  patches:
    - 0001-Allow-cross-building-packages.patch
    - 0002-Do-not-run-prerequisites.sh.patch

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
    - pkg-config
    - curl
    - automake
    - libtool
  host:
    # Since we are using bin/buildpackages.sh to build all packages at once,
    # these requirements are needed.
    - gmp
    - readline {{ readline }}
    - ncurses                    # for package Browse
    - curl                       # for package curlInterface
    # GAP uses the old header layout of cddlib that changed in 0.94k; we do not
    # build a cdd interface until this is fixed upstream; see #79.
    # - cddlib                   # for package cddInterface
    - mpfr                       # for package float
    - mpfi                       # for package float
    - mpc                        # for package float
    - pari                       # for package alnuth
    - zeromq                     # for package ZeroMQInterface
    - libsemigroups >=3.1.1,<4   # for package Semigroups
    - planarity >=3,<4           # for package digraphs
    - bliss                      # for package digraphs
    - normaliz                   # for package NormalizInterface
    - libflint                   # for package NormalizInterface -> normaliz -> e-antic -> libflint <=2.6.0
    - zlib

outputs:
  - name: gap-core
    script: install-core.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - libtool
        - make
      host:
        - gmp
        - readline {{ readline }}
        - zlib
    test:
      commands:
        - gap -h
      script: run_test.sh

  - name: gap-defaults
    script: install-defaults.sh
    requirements:
      host:
        - {{ pin_subpackage('gap-core', exact=True) }}
      run:
        - {{ pin_subpackage('gap-core', exact=True) }}
    test:
      script: run_test.sh

  # The GAP CAS with all packages that we could manage to build.
  # Eventually, we might want to split this into separate gap- packages so that
  # it is possible to install just a subset of those. (Some, such as
  # cddinterface conflict with other systems such as sage.)
  - name: gap
    script: install-full.sh
    build:
      ignore_run_exports_from:
        - python *
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - libtool
        - make
        - python *                            # [build_platform != target_platform]
        - setuptools <60                      # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
      host:
        - gmp
        - readline
        - ncurses             # for package Browse
        # GAP uses the old header layout of cddlib that changed in 0.94k; we do
        # not build cddInterface until this is fixed upstream, see #79.
        # - cddlib
        - libcurl                    # for package curlInterface
        - mpfr                       # for package float
        - mpfi                       # for package float
        - mpc                        # for package float
        - pari                       # for package alnuth
        - zeromq                     # for package ZeroMQInterface
        - libsemigroups >=3.1.1,<4   # for package Semigroups
        - planarity >=3,<4           # for package digraphs
        - bliss                      # for package digraphs
        # libnormaliz fails to detect the normaliz headers, see #84.
        # - normaliz                   # for package NormalizInterface
        # - libflint                   # for package NormalizInterface -> normaliz -> e-antic -> libflint <=2.6.0
        # The xgap package fails to detect the libX11 headers, see #83.
        # - xorg-libx11                # for package xgap
        - {{ pin_subpackage('gap-core', exact=True) }}
        - {{ pin_subpackage('gap-defaults', exact=True) }}
        # For JupyterKernel
        - setuptools <60
        - python *
        - pip
      run:
        - {{ pin_compatible('libsemigroups') }}
        - {{ pin_compatible('4ti2') }}        # [x86_64]
        - {{ pin_subpackage('gap-core', exact=True) }}
        - {{ pin_subpackage('gap-defaults', exact=True) }}
    test:
      script: run_test.sh

about:
  home: https://www.gap-system.org/
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: GAP - Groups, Algorithms, Programming, a System for Computational Discrete Algebra
  dev_url: https://github.com/gap-system/gap
  doc_url: https://docs.gap-system.org/doc/ref/chap0_mj.html

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
