{% set version = "4.11.0" %}
{% set name = "gap-split" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://www.gap-system.org/pub/gap/gap-{{ ".".join(version.split(".")[:2]) }}/tar.gz/gap-{{ version }}.tar.gz
  sha256: 6fda7af23394708aeb3b4bca8885f5fdcb7c3ae4419639dfb2d9f67d3f590abb

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
  host:
    # Since we are using bin/buildpackages.sh to build all packages at once,
    # these requirements are needed.
    - gmp
    - readline {{ readline }}
    - ncurses    # for Browse
    - curl       # for curlInterface
    - mpfr       # for float
    - mpfi       # for float
    - mpc        # for float
    #- fplll     # for float
    - pari       # for alnuth
    - zeromq     # for ZeroMQInterface
    - libsemigroups  1.0.*   # for Semigroups
    - planarity  # for digraphs
    - bliss      # for digraphs
    - normaliz   # for NormalizInterface
    - libflint 2.6.0  # for NormalizInterface -> normaliz -> e-antic -> libflint <=2.6.0
    - zlib

outputs:
  - name: gap-core
    script: install-core.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - libtool
        - make
      host:
        - gmp
        - readline {{ readline }}
        - zlib
      run:
        - gmp
        - readline {{ readline }}
        - zlib
    test:
      commands:
        - gap -h

  - name: gap-defaults
    script: install-defaults.sh
    requirements:
      host:
        - {{ pin_subpackage('gap-core', exact=True) }}
      run:
        - {{ pin_subpackage('gap-core', exact=True) }}
    test:
      commands:
        - echo "TODO - test a package here"

  - name: gap
    script: install-full.sh
    build:
      ignore_run_exports:
        - python
        - python_abi
    requirements:
      build:
        - {{ compiler('cxx') }}
        - libtool
        - make
      host:
        - gmp
        - readline {{ readline }}
        - ncurses    # for Browse
        - libcurl    # for curlInterface
        - mpfr       # for float
        - mpfi       # for float
        - mpc        # for float
        #- fplll     # for float
        - pari       # for alnuth
        - zeromq     # for ZeroMQInterface
        - libsemigroups  1.0.*   # for Semigroups
        - planarity  # for digraphs
        - bliss 0.73.*     # for digraphs
        - normaliz   # for NormalizInterface
        - libflint 2.6.0  # for NormalizInterface -> normaliz -> e-antic -> libflint <=2.6.0
        - {{ pin_subpackage('gap-core', exact=True) }}
        - {{ pin_subpackage('gap-defaults', exact=True) }}
        # For JupyterKernel
        - python *
        - pip
      run:
        - gmp
        - readline {{ readline }}
        - ncurses    # for Browse
        - libcurl    # for curlInterface
        - mpfr       # for float
        - mpfi       # for float
        - mpc        # for float
        #- fplll     # for float
        - pari       # for alnuth
        - zeromq     # for ZeroMQInterface
        - {{ pin_compatible('libsemigroups') }}   # for Semigroups
        - {{ pin_compatible('planarity') }}       # for digraphs
        - bliss >=0.73.a0,<0.74.a0       # for digraphs
        - {{ pin_compatible('normaliz') }}        # for NormalizInterface
        - {{ pin_subpackage('gap-core', exact=True) }}
        - {{ pin_subpackage('gap-defaults', exact=True) }}
    test:
      commands:
        - echo "TODO - test a package here"

about:
  home: https://www.gap-system.org/
  license: GPLv2
  license_file: LICENSE
  summary: GAP - Groups, Algorithms, Programming, a System for Computational Discrete Algebra
  dev_url: https://github.com/gap-system/gap
  doc_url: https://www.gap-system.org/Manuals/doc/ref/chap0.html

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
