{% set version = "4.13.0" %}
{% set name = "gap-split" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/gap-system/gap/releases/download/v{{ version }}/gap-{{ version }}.tar.gz
  sha256: cc76ecbe33d6719450a593e613fb87e9e4247faa876f632dd0f97c398f92265d
  patches:
    - 0001-Allow-cross-building-packages.patch
    - 0002-Do-not-run-prerequisites.sh.patch
    - 0003-Use-system-libsemigroup-even-if-pkg-config-does-not-.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
    - pkg-config
    - curl
    - automake
    - libtool
  host:
    # Since we are using bin/buildpackages.sh to build all packages at once,
    # these requirements are needed.
    - gmp
    - readline {{ readline }}
    - ncurses              # for package Browse
    - curl                 # for package curlInterface
    # GAP uses the old header layout of cddlib that changed in 0.94k; we do not
    # build a cdd interface until this is fixed upstream.
    # - cddlib             # for package cddInterface
    - mpfr                 # for package float
    - mpfi                 # for package float
    - mpc                  # for package float
    - pari                 # for package alnuth
    - zeromq               # for package ZeroMQInterface
    - libsemigroups  1.*   # for package Semigroups
    - planarity            # for package digraphs
    - bliss                # for package digraphs
    - normaliz             # for package NormalizInterface
    - libflint             # for package NormalizInterface -> normaliz -> e-antic -> libflint <=2.6.0
    - zlib

outputs:
  - name: gap-core
    script: install-core.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - libtool
        - make
      host:
        - gmp
        - readline {{ readline }}
        - zlib
      run:
        - gmp
        - readline {{ readline }}
        - zlib
    test:
      commands:
        - gap -h
      script: run_test.sh

  - name: gap-defaults
    script: install-defaults.sh
    requirements:
      host:
        - {{ pin_subpackage('gap-core', exact=True) }}
      run:
        - {{ pin_subpackage('gap-core', exact=True) }}
    test:
      script: run_test.sh

  # The GAP CAS with all packages that we could manage to build.
  # Eventually, we might want to split this into separate gap- packages so that
  # it is possible to install just a subset of those. (Some, such as
  # cddinterface conflict with other systems such as sage.)
  - name: gap
    script: install-full.sh
    build:
      ignore_run_exports:
        - python
        - python_abi
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - libtool
        - make
        - python *                            # [build_platform != target_platform]
        - setuptools <60                      # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
      host:
        - gmp
        - readline {{ readline }}
        - ncurses             # for package Browse
        # GAP uses the old header layout of cddlib that changed in 0.94k; we do
        # not build a cdd interface until this is fixed upstream.
        # - cddlib            # for package cddInterface
        - libcurl             # for package curlInterface
        - mpfr                # for package float
        - mpfi                # for package float
        - mpc                 # for package float
        - pari                # for package alnuth
        - zeromq              # for package ZeroMQInterface
        - libsemigroups  1.*  # for package Semigroups
        - planarity           # for package digraphs
        - bliss 0.73.*        # for package digraphs
        - normaliz            # for package NormalizInterface
        - libflint            # for package NormalizInterface -> normaliz -> e-antic -> libflint <=2.6.0
        - {{ pin_subpackage('gap-core', exact=True) }}
        - {{ pin_subpackage('gap-defaults', exact=True) }}
        # For JupyterKernel
        - setuptools <60
        - python *
        - pip
      run:
        - gmp
        - readline {{ readline }}
        - 4ti2                                   # for package 4ti2interface
        - ncurses                                # for package Browse
        - libcurl                                # for package curlInterface
        - mpfr                                   # for package float
        - mpfi                                   # for package float
        - mpc                                    # for package float
        - pari                                   # for package alnuth
        - zeromq                                 # for package ZeroMQInterface
        - {{ pin_compatible('libsemigroups') }}  # for package Semigroups
        - {{ pin_compatible('planarity') }}      # for package digraphs
        - bliss >=0.73.a0,<0.74.a0               # for package digraphs
        - {{ pin_compatible('normaliz') }}       # for package NormalizInterface
        - singular                               # for package liepring
        - {{ pin_subpackage('gap-core', exact=True) }}
        - {{ pin_subpackage('gap-defaults', exact=True) }}
    test:
      script: run_test.sh

about:
  home: https://www.gap-system.org/
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: GAP - Groups, Algorithms, Programming, a System for Computational Discrete Algebra
  dev_url: https://github.com/gap-system/gap
  doc_url: https://docs.gap-system.org/doc/ref/chap0_mj.html

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
