{% set version = "4.10.1" %}
{% set name = "gap-core" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://www.gap-system.org/pub/gap/gap-{{ ".".join(version.split(".")[:2]) }}/tar.gz/gap-{{ version }}.tar.gz
  sha256: b2d8800e338a6a9afdf92b06368c2e1a16b8adebffcd4c10319c1b3a4e827e45

build:
  number: 0 
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
  host:
    # Since we are using bin/buildpackages.sh to build all packages at once,
    # these requirements are needed.
    - gmp
    - readline
    - ncurses    # for Browse
    - curl       # for curlInterface
    - boost-cpp  # for NormalizInterface
    - mpfr       # for float
    - mpfi       # for float
    - mpc        # for float
    #- fplll     # for float
    - pari       # for alnuth
    - zeromq     # for ZeroMQInterface
    - linbox     # linboxing
    - libsemigroups   # for Semigroups

outputs:
  - name: gap-core
    script: install-core.sh
    requirements:
      build:    
        - {{ compiler('cxx') }}
        - libtool
        - make
      host:
        - gmp
        - readline
      run:
        - gmp
        - readline
    test:
      commands:
        - gap -h

  - name: gap
    script: install-full.sh
    requirements:
      build:    
        - {{ compiler('cxx') }}
        - libtool
        - make
      host:
        - gmp
        - readline
        - ncurses    # for Browse
        - libcurl    # for curlInterface
        - boost-cpp  # for NormalizInterface
        - mpfr       # for float
        - mpfi       # for float
        - mpc        # for float
        #- fplll     # for float
        - pari       # for alnuth
        - zeromq     # for ZeroMQInterface
        - linbox     # for linboxing
        - libsemigroups   # for Semigroups
        - {{ pin_subpackage('gap-core', exact=True) }}
      run:
        - gmp
        - readline
        - ncurses    # for Browse
        - libcurl    # for curlInterface
        - mpfr       # for float
        - mpfi       # for float
        - mpc        # for float
        #- fplll     # for float
        - pari       # for alnuth
        - zeromq     # for ZeroMQInterface
        - linbox     # for linboxing
        - {{ pin_compatible('libsemigroups') }}   # for Semigroups
        - {{ pin_subpackage('gap-core', exact=True) }}
    test:
      commands:
        - echo "TODO - test a package here"

about:
  home: https://www.gap-system.org/
  license: GPLv2
  license_file: LICENSE
  summary: GAP - Groups, Algorithms, Programming, a System for Computational Discrete Algebra
  dev_url: https://github.com/gap-system/gap
  doc_url: https://www.gap-system.org/Manuals/doc/ref/chap0.html

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
