{% set version = "4.9.3" %}
{% set name = "gap-core" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://www.gap-system.org/pub/gap/gap-{{ ".".join(version.split(".")[:2]) }}/tar.gz/gap-{{ version }}.tar.gz
  sha256: e502941e52352285e87faaf11e7f0e810eab8e38849d869fc6b9714d6cf7fe7c

build:
  number: 0 
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
  host:
    # Since we are using bin/buildpackages.sh to build alll packages at once,
    # these requirements are needed.
    - gmp
    - readline
    - ncurses    # for Browse
    - curl       # for curlInterface
    - boost-cpp  # for NormalizInterface
    - mpfr       # for float
    - mpfi       # for float
    - mpc        # for float
    #- fplll     # for float
    - pari       # for alnuth
    - zeromq     # for ZeroMQInterface

outputs:
  - name: gap-core
    script: install-core.sh
    requirements:
      build:    
        - {{ compiler('cxx') }}
        - libtool
        - make
      host:
        - gmp
        - readline
      run:
        - gmp
        - readline

  - name: gap-minimal
    script: install-minimal.sh
    requirements:
      run:
        - {{ pin_subpackage('gap-core', exact=True) }}

  - name: gap
    script: install-full.sh
    requirements:
      build:    
        - {{ compiler('cxx') }}
        - libtool
        - make
      host:
        - gmp
        - readline
        - ncurses    # for Browse
        - curl       # for curlInterface
        - boost-cpp  # for NormalizInterface
        - mpfr       # for float
        - mpfi       # for float
        - mpc        # for float
        #- fplll     # for float
        - pari       # for alnuth
        - zeromq     # for ZeroMQInterface
        - {{ pin_subpackage('gap-minimal', exact=True) }}
      run:
        - gmp
        - readline
        - ncurses    # for Browse
        - curl       # for curlInterface
        - boost-cpp  # for NormalizInterface
        - mpfr       # for float
        - mpfi       # for float
        - mpc        # for float
        #- fplll     # for float
        - pari       # for alnuth
        - zeromq     # for ZeroMQInterface
        - {{ pin_subpackage('gap-minimal', exact=True) }}

about:
  home: https://www.gap-system.org/
  license: GPLv2
  license_file: LICENSE
  summary: GAP - Groups, Algorithms, Programming, a System for Computational Discrete Algebra
  dev_url: https://github.com/gap-system/gap
  doc_url: https://www.gap-system.org/Manuals/doc/ref/chap0.html

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
