{% set version = "4.9.3" %}
{% set name = "gap" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://www.gap-system.org/pub/gap/gap4/tar.gz/gap-4.9.3.tar.gz
  sha256: e502941e52352285e87faaf11e7f0e810eab8e38849d869fc6b9714d6cf7fe7c

build:
  number: 0 
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - libtool
  host:
    - gmp
    - readline
    - ncurses
  run:
    - gmp
    - readline
    - ncurses

test:
  commands:
    - gap -h

about:
  home: https://www.gap-system.org/
  license: GPLv2
  license_file: LICENSE
  summary: GAP - Groups, Algorithms, Programming, a System for Computational Discrete Algebra
  dev_url: https://github.com/gap-system/gap
  doc_url: https://www.gap-system.org/Manuals/doc/ref/chap0.html

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
