{% set version = "4.13.0" %}
{% set name = "gap-split" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/gap-system/gap/releases/download/v{{ version }}/gap-{{ version }}.tar.gz
  sha256: cc76ecbe33d6719450a593e613fb87e9e4247faa876f632dd0f97c398f92265d
  patches:
    - 0001-Allow-cross-building-packages.patch
    - 0002-Do-not-run-prerequisites.sh.patch
    - 0003-Use-system-libsemigroup-even-if-pkg-config-does-not-.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
    - pkg-config
    - curl
    - automake
    - libtool
  host:
    # Since we are using bin/buildpackages.sh to build all packages at once,
    # these requirements are needed.
    - gmp
    - readline {{ readline }}
    - ncurses    # for Browse
    - curl       # for curlInterface
    - cddlib     # for CddInterface
    - mpfr       # for float
    - mpfi       # for float
    - mpc        # for float
    #- fplll     # for float
    - pari       # for alnuth
    - zeromq     # for ZeroMQInterface
    - libsemigroups  1.*   # for Semigroups
    - planarity  # for digraphs
    - bliss      # for digraphs
    - normaliz   # for NormalizInterface
    - libflint   # for NormalizInterface -> normaliz -> e-antic -> libflint <=2.6.0
    - zlib

outputs:
  - name: gap-core
    script: install-core.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - libtool
        - make
      host:
        - gmp
        - readline {{ readline }}
        - zlib
      run:
        - gmp
        - readline {{ readline }}
        - zlib
    test:
      commands:
        - gap -h
      script: run_test.sh

  - name: gap-defaults
    script: install-defaults.sh
    requirements:
      host:
        - {{ pin_subpackage('gap-core', exact=True) }}
      run:
        - {{ pin_subpackage('gap-core', exact=True) }}
    test:
      script: run_test.sh

  - name: gap
    script: install-full.sh
    build:
      ignore_run_exports:
        - python
        - python_abi
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - libtool
        - make
        - python *                            # [build_platform != target_platform]
        - setuptools <60                      # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
      host:
        - gmp
        - readline {{ readline }}
        - ncurses    # for Browse
        - cddlib     # for cddInterface
        - libcurl    # for curlInterface
        - mpfr       # for float
        - mpfi       # for float
        - mpc        # for float
        #- fplll     # for float
        - pari       # for alnuth
        - zeromq     # for ZeroMQInterface
        - libsemigroups  1.*   # for Semigroups
        - planarity  # for digraphs
        - bliss 0.73.*     # for digraphs
        - normaliz   # for NormalizInterface
        - libflint   # for NormalizInterface -> normaliz -> e-antic -> libflint <=2.6.0
        - {{ pin_subpackage('gap-core', exact=True) }}
        - {{ pin_subpackage('gap-defaults', exact=True) }}
        # For JupyterKernel
        - setuptools <60
        - python *
        - pip
      run:
        - gmp
        - readline {{ readline }}
        - ncurses    # for Browse
        - libcurl    # for curlInterface
        - mpfr       # for float
        - mpfi       # for float
        - mpc        # for float
        #- fplll     # for float
        - pari       # for alnuth
        - zeromq     # for ZeroMQInterface
        - {{ pin_compatible('libsemigroups') }}   # for Semigroups
        - {{ pin_compatible('planarity') }}       # for digraphs
        - bliss >=0.73.a0,<0.74.a0       # for digraphs
        - {{ pin_compatible('normaliz') }}        # for NormalizInterface
        - {{ pin_subpackage('gap-core', exact=True) }}
        - {{ pin_subpackage('gap-defaults', exact=True) }}
    test:
      script: run_test.sh

about:
  home: https://www.gap-system.org/
  license: GPL-2.0-or-later
  license_file: LICENSE
  summary: GAP - Groups, Algorithms, Programming, a System for Computational Discrete Algebra
  dev_url: https://github.com/gap-system/gap
  doc_url: https://docs.gap-system.org/doc/ref/chap0_mj.html

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
