{% set version = "4.9.0" %}
{% set name = "gap" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/gap-system/gap/archive/v{{ version }}.tar.gz
  sha256: 8d4ff0a9fad5dd66bbfc6a6e30911c2addff971db7372988b26fe91c5f620dcc
  patches:
    # Patches from https://github.com/sagemath/sage
    # fix infinite loop in writeandcheck() when writing an error message fails.
    - patches/writeandcheck.patch
    # we don't install some of the default packages
    - patches/nodefaultpackages.patch

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - libtool
    - gmp >=5.0.1,<7
    - readline 6.2*
    - ncurses 5.9*
  run:
    - gmp >=5.0.1,<7
    - readline 6.2*
    - ncurses 5.9*

test:
  commands:
    - gap -h

about:
  home: https://www.gap-system.org/
  license: GPLv2
  license_file: LICENSE
  summary: GAP - Groups, Algorithms, Programming, a System for Computational Discrete Algebra
  dev_url: https://github.com/gap-system/gap
  doc_url: https://www.gap-system.org/Manuals/doc/ref/chap0.html

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
