{% set version = "4.8.3" %}
{% set name = "gap" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://www.gap-system.org/pub/gap/gap48/tar.gz/gap4r8p3_2016_03_19-22_17.tar.gz
  sha256: 667fbbe4b6f2626b799b977a4ca12e9373e0878a6771a94d217bab412405abe6
  patches:
    # Patches from https://github.com/sagemath/sage
    # Set GAP_MEM
    - patches/gap_shi.patch
    # fix infinite loop in writeandcheck() when writing an error message fails.
    - patches/writeandcheck.patch
    # Reserve space for long paths
    - patches/long_path.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - toolchain
    - libtool
    - gmp >=5.0.1,<7
    - readline 6.2*
    - ncurses 5.9*
  run:
    - gmp >=5.0.1,<7
    - readline 6.2*
    - ncurses 5.9*

test:
  commands:
    - gap -h

about:
  home: https://www.gap-system.org/
  license: GPLv2
  license_file: LICENSE
  summary: GAP - Groups, Algorithms, Programming, a System for Computational Discrete Algebra
  dev_url: https://github.com/gap-system/gap
  doc_url: https://www.gap-system.org/Manuals/doc/ref/chap0.html

extra:
  recipe-maintainers:
    - isuruf
