travis:
  secure:
    BINSTAR_TOKEN: o31n/c5bqp59WUyPkgH1cSwOyInlDuixZWdBq+AaumCOURFLcWGTGHpKwU4p+i1GrOKp1CoF8G20woNgQSD+KWzsOvaZ0+Y5uI+P2cd9KrRDOIGnnuIc8FapgawhxUciIyRulCwynR3zhdKS3K0ZA4eNm50+g/syysFtczs6fSmH43546Gokz/32tn7KkQXEGkWmqeXwo/u30GdKFbWHkQhQ176FL9lA2j8ArAZGl8ekqkOClzXW/2JiHgUIlU+e5IaNCSQx7Q9hCJqktSpImjXUlEPFR0W/iNpqaBBkiom2XIF1gp8iIu6gF8DaDHxILZlQnBCRxBURoI5rFQpLppV4nJ5y6Ie4VIYkYsxnsW7mzK6s8+0aHd8ArTum2Pac+16/76ZcJSVfRav/FyqgVwz4SpNtvpdM51QrmX8eoxy4BCGTfTT+qnl93vo9eCBNnkhPZKE4EHxFyIoxP4qaOS0VLtPxrRIKCljfjLFHZ2Q5VPDVW/mhlo8+XJwh3kmxg3xD9YJfj5gstTZinarcUfkm813wvn1hF7b7cpGSRpb+zIH+AQFRw/Bg0FYFIl8Y4PSo2NXb/+whEabe9KXuim/oNSfMBeQIzdDngrYOlGZ1oea45UybC3Ok6b2tdRuu9IdiIPYfx/Sg7qBYiSMlj2nuuMa4TNwVDEqLfWLt7gs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
