travis:
  secure:
    BINSTAR_TOKEN: RbPmoku7DXWF2RTnUvxWwzs8B3IIyNGUd5a2vKJMSd/u1WpWCE41llSTBtud0s+/FSJRIhlfz930zfznxuTdqUzEPLRC7WCA42kVeot064Bo/PstwwwR1ZgGBh2s9Vj2cK3qlHUSkFlPUA7f/auUzngIbb78L9eK/zsYsokF7jXtzbsPLX2w7m25eAKSqYHikjtTT4GzIm/j/N8/SBOM5rATV6IvR1a05jeN3ZGfnLdhhZzEINRIVBd3q/JB0IqKSTe+8PyUc+19poN23w63EjI/hBCUpNp8e/SfEBZNtgGrXZCpOwynUGCqCgQDVpEoBzMN3v8hsPbljjuOpeLByK7Q0ZEey6cWeBtalaZYemMekRTuOodLMFUYEz/X0cegHIE13tNeKA2Gi9B3uFxiRtaJc4W/M5bm/aVqQdbamyvJ9KDluWOgVlhjMJyA1R4EWMgW3GCEycyR8of2WYrHsSaGbzfZgIHHCiVuWMgHZadZ0BhlxL4CZE2rkJZ+6bO6je6wCYpvAJAat0wYkN/4IUqpBE+2PJ8+lRKJGLjMguYN2kPXlhLZervNzatg0glfhpoDZTedxd6sAck9yzrPFYFgY991o1w8z09WEvrH/X//TJmmBglXA8YzFI3SaMPaveUTYY6bLUGOENZOOF25JuuoCA9+3ju5wLT3kHIHK50=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
